[package]
name = "aoc"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
clap = "4.5.21"
dotenv = "0.15.0"
itertools = "0.13.0"
regex = "1.11.1"
reqwest = { version = "0.12.9", features = ["blocking"] } 
